[application]

[web.app]
base_path = "/"

# HTML title tag content
title = "labubu-assets"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

# Static assets
assets = ["assets/*"]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
