name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rust-src

      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang lld build-essential pkg-config libssl-dev

      - name: Install Dioxus CLI
        run: cargo install dioxus-cli --locked

      - name: Build application with Dioxus
        env:
          CC: clang
          CFLAGS: "--target=wasm32-unknown-unknown"
        run: |
          rm -rf docs
          dx bundle --platform web --release --out-dir docs
          mv docs/public/* docs
          rmdir docs/public

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
